apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-management-service
  template:
    metadata:
      labels:
        app: team-management-service
    spec:
      containers:
        - name: team-management-service
          image: lgcollins/team-management-service:latest
          ports:
            - containerPort: 1002
          env:
            - name: TMS_NODE_ENV
              value: "development"
            - name: TMS
              value: "1002"
            - name: TMS_LOG_DIR
              value: "logs/"
            - name: TMS_API_URL
              value: "localhost"
            - name: TMS_API_PORT
              value: "1002"
            - name: TMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: TMS_API_KEY
            - name: TMS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: TMS_DB_USER
            - name: TMS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: TMS_DB_PASS
            - name: TMS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: TMS_DB_NAME
            - name: TMS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: TMS_DB_HOST
            - name: TMS_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: TMS_DB_PORT
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: API_KEYS
            - name: JWT_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: JWT_TOKEN_SECRET
            - name: JWT_TOKEN_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: team-management-service-secrets
                  key: JWT_TOKEN_EXPIRY
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
