apiVersion: v1
kind: Service
metadata:
  name: ums-management-service
spec:
  selector:
    app: ums-management-service
  ports:
    - protocol: TCP
      port: 1001
      targetPort: 1001
  type: LoadBalancer
