apiVersion: v1
kind: Secret
metadata:
  name: wwcc-validation-service-secrets
type: Opaque
data:
  UMS_API_KEY: U1RSU09OLVVNQ19BUElfS0VZ
  UMS_DB_USER: cG9zdGdyZXM=
  UMS_DB_PASS: UG9zdEdvRmxhZw==
  UMS_DB_NAME: dGVhbS1ndWFyZGlhbi11c2VyLW1hbmFnZW1lbnQtc2VydmljZQ==
  UMS_DB_HOST: bG9jYWxob3N0
  UMS_DB_PORT: NTQzMg==
  API_KEYS: U1RST05HX0dMT0JBTF9BUFBfS0VZX0EsU1RST05HX0dMT0JBTF9BUFBfMg==
  JWT_TOKEN_SECRET: c29tZS1zZWNyZXQta2V5LXk=
  JWT_TOKEN_EXPIRY: MWg=
