apiVersion: v1
kind: Service
metadata:
  name: wwcc-validation-service
spec:
  selector:
    app: wwcc-validation-service
  ports:
    - protocol: TCP
      port: 1003
      targetPort: 1003
  type: LoadBalancer
